### ISSUE TITLE
Feature Request: Sub-Tabs

### ISSUE THREAD

**Issue by Enixile** [Particle1904/DatasetHelpers#11]
With the large number of vertical tabs, it would be helpful to consolidate them and then have horizontal sub-tabs for the related functionality. For example...

General: Welcome, Settings
Pre-Filter (for quality)
Crop: Automatic, Manual
Resize: Automatic, Manual
Tag/Caption: Generate, Process Tags, Process Captions, Edit
Post-Filter (for tags/captions)
Generation: Generate Prompts, View Metadata

**Comment by Particle1904** [comment]
Yeah, sounds like something that I'll eventually have to add if I keep adding new features but for now its not in my plans.
