### ISSUE TITLE
Adjusting Output Dimension Size

### ISSUE THREAD

**Issue by nehemiahgo** [Particle1904/DatasetHelpers#13]
This is an amazing tool which has saved me so much time, you should link to a buymeacoffee or something so we can show you our support!

Is there any way we can set the output dimension sizes for content aware cropping and resizing image functions? I train data on resolutions larger than 1024x1024, and also like to future proof future checkpoints by preserving the original resolutions of my datasets. 

Would be a great feature if you could implement this or show us how to adjust this on our own?

**Comment by Particle1904** [comment]
Yes, you can select output dimension in the content aware page from 512x all the way up to 1024x. If I recall correctly, it will programmatically upscale if the image is smaller than the target dimension; I had plans on adding a way to upscale images with AI but didn't managed to figure out how to convert them to .onnx to be used with C#.

**Comment by nehemiahgo** [comment]
Thanks for responding Particle1904! Yes, but can that dropdown be adjusted to something larger like 2048px? The problem I am having is my source images are larger than the target dimensions.
I'd love to be able to use the auto cropping or even resize functionality and I'm even OK with it downscaling them to something like 2048px, but 1024px would be too small.

**Comment by Particle1904** [comment]
Sorry, I don't understand... The source images can be any size.
But yeah, I can add 2048x.

**Comment by Particle1904** [comment]
This was added in the next release. Sorry for the long delay.

![image](https://github.com/Particle1904/DatasetHelpers/assets/6633799/7f9dc198-542b-4921-84b0-a1c4ae6c9c87)
