### ISSUE TITLE
Tag or Caption Editor

### ISSUE THREAD

**Issue by angry-orange** [Particle1904/DatasetHelpers#17]
Hello, thank you for your work.

By following the guidelines at <<https://github.com/Particle1904/DatasetHelpers/wiki/Editor-Page>> I see something that looks like a regression in "Tag/Caption Editor".

What was tried:

Run as administrator.
Rename the file to a legitimate name instead of UUID or anything.

Dataset Example
![Captura de tela 2024-03-09 122713](https://github.com/Particle1904/DatasetHelpers/assets/27979775/a6027d0e-25b6-4530-bb20-88608c75205b)

Version 1.6.1
![Captura de tela 2024-03-09 122138](https://github.com/Particle1904/DatasetHelpers/assets/27979775/07070fc3-1048-4db2-8391-3dd5dcdbfd62)
![Captura de tela 2024-03-09 122123](https://github.com/Particle1904/DatasetHelpers/assets/27979775/627f078e-acdd-44f0-81ca-d3a6499bb8b4)

Version 2.3.0
![Captura de tela 2024-03-09 122219](https://github.com/Particle1904/DatasetHelpers/assets/27979775/45ee9544-817a-4c27-a162-d9ebfd468528)
![Captura de tela 2024-03-09 121904](https://github.com/Particle1904/DatasetHelpers/assets/27979775/125ba7d6-b709-4d8e-9dee-fc62c76c13e6)

**Comment by Particle1904** [comment]
Hello. Can you clarify?
I don't really understand what is the issue here.

**Comment by angry-orange** [comment]
> Hello. Can you clarify? I don't really understand what is the issue here.

The content that is inside the captions files is not showed, changed et cetera.

**Comment by Particle1904** [comment]
Oh... Seems like I broke it; somehow.
I haven't touched the editor page in a while.

**Comment by Particle1904** [comment]
Its working in v2.2.0; if you want to use that for now while I fix this.

**Comment by angry-orange** [comment]
> Its working in v2.2.0; if you want to use that for now while I fix this.

Right. Thank you for your desire to help.

**Comment by Particle1904** [comment]
There's a new release up that fixes that issue: https://github.com/Particle1904/DatasetHelpers/releases/tag/v2.3.1
Thanks for reporting it!
