### ISSUE TITLE
[Request] Caption style tagging like BLIP

### ISSUE THREAD

**Issue by Bercraft** [Particle1904/DatasetHelpers#19]
Could be possible to add a something like BLIP?? thank you

**Comment by Particle1904** [comment]
You can generate captions with other tools out there and my tools will be able to deal with .caption text files (although it's limited at this moment).

I explained in this post why models like BLIP currently aren't supported: https://github.com/Particle1904/DatasetHelpers/issues/14#issuecomment-1951163757

I've tried before but I'm simply lacking the necessary knowledge to implement inference for caption models that use tokenization. Furthest I got was converting a model like BLIP to .onnx format.
I could be lazy and use interop with Python... and C# is great at it, but I personally I'm not using the tools that much lately and it's mostly not being developed anymore, unless I need a new feature; which happens very rarely nowdays.

**Comment by Bercraft** [comment]
Thank you i understand.
