### ISSUE TITLE
Great Tool!

### ISSUE THREAD

**Issue by Seantourage** [Particle1904/DatasetHelpers#2]
Looking forward to the next release. Using it to train photo subjects I made a few tweaks to the tagging that you might want to use in the wiki.

**Removed tags**: These are the tags I remove from each photo.

`real life insert, solo, solo focus, female focus, male focus, solo male focus, solo female focus, mature male, mature, female, muscular male, old woman, fat, fat man, bokeh, blurry background, depth of field, simple background, photo background, grey background, white background, black background, purple background, orange background, horror (theme), star (symbol), photo (object), genderswap (mtf), lips, teeth, nose, forehead, freckles, collarbone, armpits, navel, thick eyebrows, brown eyes, blue eyes, green eyes, black eyes, birthmark, facial mark, scar, mole, mole on cheek, mole under eye, mole on neck, mole under mouth, mole above mouth, mole on body, mole on breast, breasts, nipples, small breasts, medium brests, large breasts, very dark skin, dark skinned, dark skin, dark-skinned male, dark-skinned female, wrinkled skin, colored skin`

**Replaced Tags**
`1girl, 1boy, realistic, topless male, poster (object), painting (object), bar (place), canvas (object), mouse (computer), painting (medium)`
with
`woman, man, photo, topless, poster, painting, bar, canvas, computer mouse, painting`

I'm debating also removing "looking at viewer" since it's so typical.

Also using a 0.25 I did an auto caption of 8000+ photos and these were the most common tags. Used this as a reference for the above (see attached)

[tag_occurrences_sorted.txt](https://github.com/Particle1904/DatasetHelpers/files/12678913/tag_occurrences_sorted.txt)

**Comment by Particle1904** [comment]
Hi! How are you doing?
I'm glad you find the tool useful.
I don't really understand what is the _issue_.
But if you are suggesting to automatically change or remove tags, its not something I want to do since the tools are supposed to work with booru tags and artwork.
Although it works with photographs, its a good idea to also have english captions alongside them.

**Comment by Seantourage** [comment]
Mainly a thanks and comment since you don't have discussions enabled, just wanted to reach out.
