### ISSUE TITLE
[Feature Request] Support for Additional Languages

### ISSUE THREAD

**Issue by thiagojramos** [Particle1904/DatasetHelpers#21]
I would like to request support for additional languages in the Dataset Processor AiO, specifically for pt-BR. I am available to assist with the translation to pt-BR.

Thanks!

**Comment by Particle1904** [comment]
I could translate it myself since pt-br is my native language. Just not sure if I want to go through the implementation side of it since I'm currently working on tools to clean up text/watermark/logos in images automatically or manually.
