### ISSUE TITLE
App doesn't show images

### ISSUE THREAD

**Issue by Enferlain** [Particle1904/DatasetHelpers#22]
Tried a few folders and it says how many images are in them but they're not visible in the gallery or other tabs. Installed the runtimes then downloaded the release and ran the exe. What do I do?

![image](https://github.com/Particle1904/DatasetHelpers/assets/15861396/2383fc32-4c9d-4ba8-b515-9970b5a8906c)

**Comment by Particle1904** [comment]
Hum, I'm not sure.
The application only loads images in the top folder, so anything in subfolders is ignored.
Do you have anything inside the logs folder?
![image](https://github.com/Particle1904/DatasetHelpers/assets/6633799/e6290f38-8fc4-4375-82b3-ebdc8fc69e4c)

**Comment by Particle1904** [comment]
Closing the issue since you didn't reply. Feel free to open it again.
