### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JLipnerPitt** [Particle1904/DatasetHelpers#25]
The Tag/Caption editor crashes in the latest version of the Windows x64 build. I tested it with a single image and txt file named 1, respectively, and it still crashed the software. I tried the previous release version and didn't have this issue. Basically, the app shows the first image in any folder and then crashes.

**Comment by Particle1904** [comment]
I see what is the problem, its trying to load the cliptokenizer but I removed the code that downloads it by accident.
Download [this file](https://huggingface.co/Crowlley/DatasetToolsModels/blob/main/cliptokenizer.onnx) and place it inside the <appRootFolder>/models folder

**Comment by JLipnerPitt** [comment]
I think you might have split the code into two folders. You have a source code folder that doesn't do anything, and you have a windows x64 folder that runs the code. Are these two folders supposed to be combined? Regardless, neither one has an applicationRootFolder.

**Comment by Particle1904** [comment]
Yes, the code that downloads the file also creates the folder.
