### ISSUE TITLE
[BUG] Inpaint Issues

### ISSUE THREAD

**Issue by JLipnerPitt** [Particle1904/DatasetHelpers#27]
### Bug Description
Each time an image is selected, another image with a black background is created and saved in the image directory. It doesn't matter whether the inpainting action occurred, or not. Also, I'm not sure if it's intentional or not, but two different versions of the same image are displayed in the inpaint window. I believe a memory leak is probably the root cause of the issue because eventually, the program will crash if enough of the black background images are created.

Aside from those issues, the actual inpainting process itself works. However, I would recommend making the inpainted image override the old image each time inpainting takes place.

![image](https://github.com/Particle1904/DatasetHelpers/assets/122459494/33773d26-0d4f-4764-9aba-cd00373be03d)
![image](https://github.com/Particle1904/DatasetHelpers/assets/122459494/f654345f-f957-4dc1-8518-6ef56f160a14)

This is for the desktop version.

**Comment by Particle1904** [comment]
The black image is the mask image and it's intentional that one is created every time a new image is selected. This was done for 2 reasons: the mask can also be used for training models with an attention mask (and someone asked for that feature months ago) and to not keep hundreds of masks loaded in memory.
Showing the same image two times in the UI is also intentional, maybe not necessary but I like the option to see the image without the mask on top of it.
The inpainting overriding the original image isn't going to happen because not doing destructive operations is a development choice I made, I lost a 270 images dataset when I first started developing the tools and I don't want that to happen to anyone else. If you want to inpaint the same image again then you can copy the output image back to the input folder. I could add a button to copy the output image back to the input folder but it won't happen automatically.

About the crash, if you can check your Windows Event Logs for a log about the crash that would be helpful in finding out why it crashed. It could be a number of things but I don't think it's a memory leak, there's a possibility that you painted and it failed to save so it crashed.

**Comment by JLipnerPitt** [comment]
I see. Are you willing to add an option to toggle it off or on? Or even make it so that a folder gets created in the image directory that is for the masks themselves? The button option would be great. It's tedious to delete each inpainted image.

Here's the crash log: 
Faulting application name: DatasetProcessorDesktop.exe, version: 1.0.0.0, time stamp: 0x661f0000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab
Exception code: 0xe0434352
Fault offset: 0x000000000006543c
Faulting process id: 0x0x4898
Faulting application start time: 0x0x1DAB3E27E007E34
Faulting application path: C:\Users\iamth\Desktop\Dataset Editor\win-x64\DatasetProcessorDesktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: c5209854-730b-4707-a74e-d371aac277d0
Faulting package full name: 
Faulting package-relative application ID:

**Comment by Particle1904** [comment]
Unfortunately the crash doesn't help at all, its just saying the crash happened in .NET somewhere.
I think a folder for the masks is a good compromise and a better way to organize the files. I'll make that change.

**Comment by JLipnerPitt** [comment]
Thank you, I look forward to it.

What about this crash log:

Exception Details
=================
Date and Time: 2024-06-02 00:06:31
Source: System.Private.CoreLib
Message: The input string '08032cc181d856cce693eed840a08d70' was not in a correct format.
Help Link: 
HResult: -2146233033

Stack Trace
============
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Int32.Parse(String s)
   at DatasetProcessor.ViewModels.GalleryViewModel.<>c.<LoadImagesFromInputFolder>b__18_1(String x) in E:\dev\DatasetHelpers\DatasetProcessor\ViewModels\GalleryViewModel.cs:line 130
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.Fill(Buffer`1 buffer, Span`1 destination)
   at System.Linq.OrderedEnumerable`1.ToList()
   at DatasetProcessor.ViewModels.GalleryViewModel.LoadImagesFromInputFolder() in E:\dev\DatasetHelpers\DatasetProcessor\ViewModels\GalleryViewModel.cs:line 130

Target Site
============
Declaring Type: System.Number
Method Name: ThrowFormatException

Additional Information
======================

**Comment by Particle1904** [comment]
Already fixed that one, its trying to sort but the image file name isn't numerical.
https://github.com/Particle1904/DatasetHelpers/issues/26#issuecomment-2143790830
If it can't sort, it will just display the files without sorting.

**Comment by JLipnerPitt** [comment]
Thank you. I'll wait for the next version. I don't change the names as a way to keep track of the images I've obtained from the booru websites.

**Comment by Particle1904** [comment]
> I see. Are you willing to add an option to toggle it off or on? Or even make it so that a folder gets created in the image directory that is for the masks themselves? The button option would be great. It's tedious to delete each inpainted image.
> 
> Here's the crash log: Faulting application name: DatasetProcessorDesktop.exe, version: 1.0.0.0, time stamp: 0x661f0000 Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab Exception code: 0xe0434352 Fault offset: 0x000000000006543c Faulting process id: 0x0x4898 Faulting application start time: 0x0x1DAB3E27E007E34 Faulting application path: C:\Users\iamth\Desktop\Dataset Editor\win-x64\DatasetProcessorDesktop.exe Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll Report Id: c5209854-730b-4707-a74e-d371aac277d0 Faulting package full name: Faulting package-relative application ID:

All the other fixes are done.
Can you clarify what you mean by "The button option would be great. It's tedious to delete each inpainted image."?
My suggestion was to create a button to copy the inpainted image (for the current selected image in the UI) from the output (if it exists) folder back to the input folder.

**Comment by Particle1904** [comment]
Hotfix for the discussed problems: https://github.com/Particle1904/DatasetHelpers/releases/tag/v2.8.1
Let me know if there's any problems.

**Comment by JLipnerPitt** [comment]
> > I see. Are you willing to add an option to toggle it off or on? Or even make it so that a folder gets created in the image directory that is for the masks themselves? The button option would be great. It's tedious to delete each inpainted image.
> > Here's the crash log: Faulting application name: DatasetProcessorDesktop.exe, version: 1.0.0.0, time stamp: 0x661f0000 Faulting module name: KERNELBASE.dll, version: 10.0.22621.3527, time stamp: 0x83efbeab Exception code: 0xe0434352 Fault offset: 0x000000000006543c Faulting process id: 0x0x4898 Faulting application start time: 0x0x1DAB3E27E007E34 Faulting application path: C:\Users\iamth\Desktop\Dataset Editor\win-x64\DatasetProcessorDesktop.exe Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll Report Id: c5209854-730b-4707-a74e-d371aac277d0 Faulting package full name: Faulting package-relative application ID:
> 
> All the other fixes are done. Can you clarify what you mean by "The button option would be great. It's tedious to delete each inpainted image."? My suggestion was to create a button to copy the inpainted image (for the current selected image in the UI) from the output (if it exists) folder back to the input folder, essentially overwriting the non-inpainted input image.

I'll give a try and let you know of any problems I encounter. 

The biggest issue with inpainting and even cropping right now is that the original image stays in the folder. So, let's say I crop 100 images or inpaint 100 images. I have to find the original images inside the folder and delete them, since they're not overridden by either action.

**Comment by Particle1904** [comment]
Why don't you select a different folder for the output? I just now understood that you are using the same folder path for the input and output. The intended behaviour is to use an input and an output folder.

It does filter by excluding the files that have the given tag, but doing a search with another tag like "dog" will overwrite it. If you filter like "dog, !car" it will filter out images tagged with car and get images with "dog" even if there's "car" in the tags.

**Comment by JLipnerPitt** [comment]
The same issue would persist, just in a different way. If I chose a different folder output, the output images would be in a different folder, sure, but I cropped the original image or inpainted it for a reason. I'd still have to find it in the original directory and delete it, then copy the edited image to that dataset.

Wouldn't it make more sense to filter images that include "dog" AND don't have "car"? Otherwise, in that case, it's just the same as a normal search.

**Comment by Particle1904** [comment]
I have to think more about this, its gonna require a lot of changes to respect file formats, it used to be like that before I even implemented an user interface. I'm still leaning towards using one single file type is preferable for many reasons. Working with one input and one output folder is also preferable. I've had others complain before that they lost their files and I don't want to deal with that again, even when I give users responsibility, it ends up being my fault.
For now, if you really want to override existing files, I suggest using a python script to convert your images to .jpeg before using the dataset processor.
