### ISSUE TITLE
"Tags to add" do not work for images without text file

### ISSUE THREAD

**Issue by WorldEntityGravity** [Particle1904/DatasetHelpers#30]
### Bug Description
When creating a new dataset and using the "Tags to add" textbox on the "Process Tags" page, no new text files are created, only existing text-files are tagged.

### Steps to Reproduce
Create a new folder with images
Do not add any text files for the images
Open the "Process Tags" page and fil in the "Tags to add" text box
Click on the "Process tags" button
Nothing happens

### Expected Behavior
When trying to add tags to images without a text file, it should create a text file and add the tags to it or have a option (checkbox?) for it

### Environment Details
Complete the following information:
- Operating System: Windows 11
- Application Version: 2.8.1

**Comment by Particle1904** [comment]
Not really a bug, it was just a design choice. The page is supposed to be used to process existing files.
