### ISSUE TITLE
[Feature Request] Image similarity/duplicate

### ISSUE THREAD

**Issue by DEX-1101** [Particle1904/DatasetHelpers#31]
sometime while scrapping stuff (danbooru mostly), there might be 2 post of same pic but with different resolution so it will be good if can detect those and automatically remove one of them and also can be removed manually by choosing one among those similar stuff it will be very helpful if that possible, thanks !

**Comment by O-J1** [comment]
> sometime while scrapping stuff (danbooru mostly), there might be 2 post of same pic but with different resolution so it will be good if can detect those and automatically remove one of them and also can be removed manually by choosing one among those similar stuff it will be very helpful if that possible, thanks !

Look into either a simple phash script or alternatively the easy mode is DupeGuru.

**Comment by Particle1904** [comment]
Its a planned feature but its a bit more complicated than it sounds. At the moment, I'm using AllDup for it.
