### ISSUE TITLE
[Feature Request] Add the latest SmilingWolf tagging model.

### ISSUE THREAD

**Issue by irldoggo** [Particle1904/DatasetHelpers#33]
It looks like SmilingWolf has just released a new tagger https://huggingface.co/SmilingWolf/wd-eva02-large-tagger-v3
If it could be added, that would be great!

Thanks for the amazing tool. Has already saved me countless hours.

**Comment by Particle1904** [comment]
There's an open pull request for it. Should be available in v2.9.0 when I get some time to check the PR out and merge.

**Comment by Particle1904** [comment]
Here's the release with the large model: https://github.com/Particle1904/DatasetHelpers/releases/tag/v2.9.0
Let me know if you find any issues with it.
