### ISSUE TITLE
[REQUEST} Custom WD tags

### ISSUE THREAD

**Issue by BenDes21** [Particle1904/DatasetHelpers#35]
Hi there! Sorry to post in the issues section but I don't see the discussion tab.

Would like to know if it's possible to allow the user to use specific WD taggers ( like the ones from [smiling wolf ](https://huggingface.co/SmilingWolf)  )

Thanks a lot for your amazing tool

**Comment by BenDes21** [comment]
> Are you asking because you want to use the new "wd-eva02-large-tagger-v3" model? If yes, I'll add support for it today. It will be available in v2.9.0 version.

Hi there ! Thanks a lot! Yes my request was for wd-eva02-large-tagger-v3 and wd-vit-large-tagger-v3 :) 

Have a great day

**Comment by Particle1904** [comment]
Here's the release with the large model: https://github.com/Particle1904/DatasetHelpers/releases/tag/v2.9.0
Let me know if you find any issues with it.
