### ISSUE TITLE
[BUG] Tag/Caption Editor crashes the program whenever I try to filter images by a specific tag

### ISSUE THREAD

**Issue by Iagmon** [Particle1904/DatasetHelpers#40]
### Bug Description
Tag/Caption Editor crashes the program whenever I try to filter images by a specific tag. Does not happen if I search for a negative tag (eg, filtering by "-1boy" will not crash, but filtering by "1boy" will). I'm using the 64x version of the program.

Other features of the Tag/Caption Editor function normally.

Couldn't find any log folder in the root folder, so I assume the program didn't create any logs at all?

### Steps to Reproduce
Outline the steps to reproduce the behavior:

Open Program
Go to Tag/Caption Editor
Select an input folder with images that have already been tagged
Enter a tag in the filter's text box.
Click on "Filter Images" or press enter
Program freezes then crashes

### Expected Behavior
Program shouldn't crash

### Screenshots
Non-applicable

### Environment Details
Complete the following information:
- Operating System: Windows
- Application Version: Program says it's 2.8, but I just downloaded and installed the latest version (2.9.0) and it still says 2.8, so I assume it's actually 2.9 and the 2.8 number just hasn't been changed in the latest version.

**Comment by Iagmon** [comment]
I've figured this one out.

I had installed the program in C:/ProgramFiles/Dataset Processor 2.9.0. For some reason, moving it to a location outside C:/ProgramFiles made the program function correctly again.

I assume it has something to do with being denied permissions when installed under C:/ProgramFiles

**Comment by Iagmon** [comment]
I don't know how to close the issue. :(

**Comment by Particle1904** [comment]
Yes, very likely to be problems with permissions. I've had other users having the same problem before. And also yes, I forgot to update the software version when I made the 2.9 release. I should probably look into automating that in the future.
