### ISSUE TITLE
Dataset Processor Desktop on Surface Pro 9

### ISSUE THREAD

**Issue by koirasp** [Particle1904/DatasetHelpers#41]
Hi
I used DPD for tag generation at home with success but now I am abroad with only my Surface Pro at hand. When using JoyTag on 0.5 threshold, it generates some general, sometimes irrelevant tags. But when I set it to 0.49, it starts to create hundreds of tags for each image and freezes the whole computer with itself before finishing with the first image. On other tagger models, the tags are completely irrelevant. I guess it's a compatibility problem with the graphic card of the tablet.

### Steps to Reproduce
Navigate to 'Generate Tags'
Select input and output folders
Select JoyTag as the tagger model and set the threshold on 0.49
(Changing other settings doesn't make a difference)
Complete freeze after a few seconds

### Expected Behavior
I hoped it worked like it did on the other PC.

### Environment Details
Device model: Microsoft Surface Pro 9
Processor: 12th Gen Intel(R) Core(TM) i7-1265U   2.70 GHz
Installed RAM: 16.0 GB (15.8 GB usable)
System type: 64-bit operating system, x64-based processor
Pen and touch: Pen and touch support with 10 touch points
OS: Windows 11 Pro
Version: 23H2
OS build: 22631.4169
Experience: Windows Feature Experience Pack 1000.22700.1034.0
Application Version: 2.9.0

### Additional Context
I did a clean re-installation of whole Windows OS. I tested several types of images. The issue persists.

**Comment by koirasp** [comment]
Missed a step to reproduce in the post above:
_(Changing other settings doesn't make a difference)_
**Hit 'Generate tags'**
_Complete freeze after a few seconds_

**Comment by Particle1904** [comment]
I honestly have no idea about how to help you out. It should work since its running on Windows and DirectML if it fails to find a GPU.

**Comment by koirasp** [comment]
Thank you! It's win-x64. I just downloaded it again and tested it. Now it created similar (irrelevant) tags for every image on 0.49:

> multiple girls, large breasts, food, multiple boys, jewelry, open mouth, blue eyes, hat, black panties, nose blush, gloves, skirt, underwear, collared shirt, looking at viewer, smile, sitting, original, looking at another, blonde hair, english text, thighhighs, sleeveless dress, hair ribbon, heart, holding weapon, boots, bow, yuri, blunt bangs, black hair, full body, brown hair, touhou, shoes, lying, eyebrows visible through hair, 1boy, ass, navel, tail, hair ornament, long sleeves, cloud, frills, standing, indoors, school uniform, closed eyes, tongue out, sidelocks, thighs, hair between eyes, cleavage, flower, swimsuit, 3girls, bag, comic, twintails, wings, makeup, muscular, bare shoulders, outdoors, jacket, animal ears, nail polish, braid, monochrome, photoshop (medium), pink hair, blurry, belt, cum, sweat, closed mouth, red hair, 1girl, shorts, :d, parody, collarbone, pantyhose, tears, white shirt, sky, signature, striped, white background, open clothes, v-shaped eyebrows, teeth, lips, :o, glowing, barefoot, sweatdrop, bra, bikini, nipples, armpits, multicolored hair, short sleeves, hand up, armor, ahoge, no humans, bare legs, on bed, fruit, purple hair, fingernails, colored skin, artist name, pussy, japanese clothes, day, alternate costume, blue hair, stomach, halterneck, upper body, expressionless, battle, hairband, cup, 6+girls, clothing cutout

On 0.4, it freezed again. I hope this helps. If there's a need to check or track anything, tell me how to and I will do.

**Comment by Particle1904** [comment]
I couldn't find any info about this issue.
