### ISSUE TITLE
[Feature request] support new wdv3 large eva2 model

### ISSUE THREAD

**Issue by Hugs288** [Particle1904/DatasetHelpers#45]
https://huggingface.co/SmilingWolf/wd-eva02-large-tagger-v3

**Comment by Particle1904** [comment]
It's already supported by the tools. It just doesn't show the full name; it's the "WD Large model" or something along those lines.
See this pull request: https://huggingface.co/Crowlley/DatasetToolsModels/discussions/1
https://github.com/Particle1904/DatasetHelpers/pull/34
