### ISSUE TITLE
[Bug] Unfinished downloading models leads to unexpected behavior

### ISSUE THREAD

**Issue by SheeperGit** [Particle1904/DatasetHelpers#46]
### Bug Description
2 bugs:
Bug 1 - The app is unable to download the wdV3LargeModel.onnx (doesn't even get to wdV3LargeTags.csv)
Bug 2 - When wdV3LargeModel.onnx and wdV3LargeTags.csv are placed in the `models/` folder, the app doesn't recognize the `input_1:0` metadata entry.

### Steps to Reproduce
1) Download Latest Release from Github. (v2.9.0, as of writing)
2) Navigate to project root directory.
3) `chmod +x DatasetProcessorDesktop`
3.5) For Bug 2, I tried downloading both wdV3LargeModel.onnx and wdV3LargeTags.csv from https://huggingface.co/Crowlley/DatasetToolsModels/tree/5d6b85a7d3fa9234b11fc45689f0c5817e2d2937 and https://huggingface.co/SmilingWolf/wd-eva02-large-tagger-v3/tree/main with the same result seen in Bug 2 Error Log.
4) `./DatasetProcessorDesktop`
5) Set input/output folders, select `wdV3Large` as the taggermodel.
6) Within 2secs, app halts and error logs are generated. (See below)

### Expected Behavior
For Bug 1, the app should download the necessary files to run the job specified. (wdV3LargeModel.onnx and wdV3LargeTags.csv, in this case)
For Bug 2, the app should recognize the downloaded files and use them for the job without error.

### Environment Details
- Operating System: Arch Linux (Kernel Version: Linux 6.12.1-arch1-1)
- Application Version: v2.9.0

### Error Logs
Bug 1: [error_2024-12-15_23-20-53.txt](https://github.com/user-attachments/files/18144891/error_2024-12-15_23-20-53.txt)
Bug 2: [error_2024-12-15_23-13-48.txt](https://github.com/user-attachments/files/18144880/error_2024-12-15_23-13-48.txt)

Thanks for reading this bug report to the end!
Let me know what details I can provide to help with the debugging process.

**Comment by Particle1904** [comment]
I can't take a look into it at this moment in time since I moved to a new place (to another state) and my furniture haven't arrived yet, which includes my PC Case and PSU. If you happen to have a file inside the logs folder, could you please send me that? It's quite hard for me to test out the Linux build so it almost always ends up with problems in new versions. The original model in the SmillingWolf won't work since I changed some layer names in the model onnx file to follow the same names of the other models, which means the only version of the model compatible with my tools is the one in my hugging face directory.

**Comment by Particle1904** [comment]
You are the 2 user so far who had problems with the automatic download, but it's a different one. The first user was also a windows user, so there's probably something Linux specific that I should've done in the download code. The logs just says that the file doesn't exist and that the input layer name is wrong.

**Comment by SheeperGit** [comment]
I've made a silly mistake :)
I didn't wait for the download to finish, so the bug I found was different from the two I initially thought they were. The program works as expected, I've tested it against all of the tools I usually use. 

The first time I've tried to download the wdV3LargeModel, I saw the `Downloading <model-name-here>...` dialogue and it had stopped while the timer kept going. I had assumed something went wrong and closed the application. It is only now that I realize that I've closed the application mid-download.

In actuality, the bug I found is likely not related to the OS platform at all. Here's my theory as to what happened:

When the user starts a download, the application records the file to be in a "downloaded" state, and expects the file to be in its appropriate location. By closing the application before the download is completed, the error found in Bug 1 is produced. 

As you've said, what I called Bug 2 is as a result of my downloading of a different file online from what the application expected. This is therefore not a bug, and in fact, intended behavior. 

It is only Bug 1 that needs fixing by verifying that the file has been downloaded _to completion._


I would suggest the first user you've described to delete the `models/` folder, delete whatever part of some file is responsible for recording whether a model file has been downloaded, and retry while being patient with the download according to their download rate. Otherwise, a full re-install can also be done with the same effect.

Sorry for the confusion from this bug. _Perhaps consider leaving the download message until the file has finished downloading instead of some default time?_ I will change the title of this issue so it's easier for other users who are experiencing this issue to find this solution. 


Thank you for being such an awesome maintainer!
Best of luck with your move, my friend.

**Comment by SheeperGit** [comment]
To add some more notable info, the v2.9.0 release page claims that .NET version 8.2.0>= is needed, but still links to the Microsoft .NET version 8.0.0 download page. I'm not sure whether the mistake is related to the site link or the version number listed on the release page, but the software has been usable for me on my machine using dotnet-runtime 8.0.10.sdk110-1on Arch Linux for the `Generate Tags`, `Process Tags`, and `Tag/Caption Editor` pages.

**Comment by Particle1904** [comment]
Should be fine as long as you have 8.0 or newer.

**Comment by Particle1904** [comment]
I've added some fixes to both problems.
The program shouldn't close anymore as long as a file is being downloaded which should fix both problems.
Completely unrelated to this issue but I've also made it so the software will automatically download the LaMa model for inpainting which it wasn't doing before.
