### ISSUE TITLE
Instructions for running on Mac

### ISSUE THREAD

**Issue by beefsan** [Particle1904/DatasetHelpers#6]
I'm able to run this on my M1 but it should be doable on Intel(I'm not very tech savvy outside troubleshooting basics and navigating)

Steps:

1. Download the file from Particle’s GitHub [(https://github.com/Particle1904/DatasetHelpers/releases)] (Source code zip)

2. Download the required dependencies [https://dotnet.microsoft.com/en-us/download/dotnet/7.0] (I don’t believe c++ is needed for it to run on Mac but I’m not positive. I used visual studio code with the c# plugin but was able to setup and run in terminal)

3. Go to: SmartData.Lib folder and open SmartData.Lib.csproj with Textedit 
3 sentences down Delete ;net7.0-windows10.0.19041.0
It should look like this:
  <PropertyGroup>    <TargetFramework>net7.0</TargetFramework>

4. Go to the folder DatasetProcessor.Desktop

5. Right click: New Terminal at Folder

6. Paste **_dotnet build /restore /t:build /p:TargetFramework=net7.0 /p:Configuration=Release /p:Platform=x64 /p:PublishSingleFile=true /p:PublishTrimmed=false /p:RuntimeIdentifier=osx-x64_**
(You should see 
Build succeeded.
    0 Warning(s)
    0 Error(s)

7. When you want to run the app open the terminal from the DatasetProcessor.Desktop folder and type: dotnet run

(I use visual studio code 
Version: 1.84.2)

Thanks for such a great set of tools!

**Comment by Particle1904** [comment]
Oh! Cool. Thanks for contributing with my project!
I'll pin this issue so people can figure out how to run on Mac.
